name: Update submodules

on:
  repository_dispatch:
    types: [update-submodules]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update submodules
        run: |
          git submodule update --init --recursive --remote

      - name: Commit and push if changes
        run: |
          if ! git diff --quiet; then
            git add WoofWoof-backend WoofWoof-frontend
            git commit -m "chore: update submodules to latest"
            git push origin main
          else
            echo "✅ Submodules déjà à jour"
          fi
